### ISSUE TITLE
Device update не обновляет notifDay and notifTime

### ISSUE THREAD

**Issue by YashaSudama** [Pronik2009/VaiCal#4]
В EndPoint /devices​/update​/{id} есть поля "notifyDay" и "notifyTime". Когда я пытаюсь их изменить на своей стороне, то они не обновляются.

**Comment by Pronik2009** [comment]
notification can't set to false - `{
  "errors": {
    "type": "https://symfony.com/errors/validation",
    "title": "Validation Failed",
    "detail": "[notification]: This value should not be blank.",
    "violations": [
      {
        "propertyPath": "[notification]",
        "title": "This value should not be blank.",
        "parameters": {
          "{{ value }}": "false"
        },
        "type": "urn:uuid:c1051bb4-d103-4f74-8988-acbcafc7fdc3"
      }
    ]
  }
}`

**Comment by Pronik2009** [comment]
notify on\off switcher also had not updating

**Comment by Pronik2009** [comment]
fixed
