### ISSUE TITLE
Добавить проверку на города, которые попадают в раздел New city

### ISSUE THREAD

**Issue by YashaSudama** [Pronik2009/VaiCal#7]
В админку сейчас попадают города, которых нет в базе, повторно. То есть, если есть в разделе New city, например город Никополь и кто-то с телефона опять отправляет его в базу, то он сейчас добавляется, а по логике не должен добавляться

**Comment by Pronik2009** [comment]
Done. Now front APP will not receive custom validator's message, just regular DB error: 
`  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Perímetro Urbano Santiago de Cali' for key 'new_city.UNIQ_D9B6B6E95E237E06'",`
